# Set InfluxDB connection configuration
INFLUXDB_HOST=''
INFLUXDB_PORT=8086
INFLUXDB_ID=''
INFLUXDB_PASSWORD='121'
INFLUXDB_DATABASE=''

# Set SFTP connection configuration
SFTP_HOST=''
SFTP_PORT=22
SFTP_USER=''
